linters:

  BorderZero:
    enabled: false

  BangFormat:
    enabled: true

  DuplicateProperty:
    enabled: true

  PseudoElement:
    enabled: true

  SingleLinePerProperty:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: true

  SpaceAroundOperator:
    enabled: true

  SpaceBeforeBrace:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true

  BemDepth:
    enabled: true

  Indentation:
    severity: warning
    width: 2

  MergeableSelector:
    enabled: true

  NameFormat:
    enabled: true

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true

  StringQuotes:
    enabled: false

  UrlFormat:
    enabled: false

# vim: sw=2 ts=3
