array_layout = "Visual"
chain_indent = "Visual"
chain_split_single_child = true
control_brace_style = "ClosingNextLine"
fn_args_layout = "Visual"
fn_brace_style = "PreferSameLine"
fn_call_style = "Visual"
fn_empty_single_line = false
fn_single_line = true
impl_empty_single_line = false
item_brace_style = "PreferSameLine"
where_density = "Compressed"
normalize_comments = true
reorder_imported_names = true
use_try_shorthand = true
reorder_imports = true
reorder_imports_in_group = true
struct_field_align_threshold = 20
struct_lit_multiline_style = "ForceMulti"
